[package]
name = "testbot"
version = "0.1.0"
authors = ["Travis Carr <tmcarr89@gmail.com>"]
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# dhb-postgres-heroku = "0.1.0-alpha.4"
env_logger = "0.6"
kankyo = "0.2.0"
log = "0.4"
pickledb = "0.4.1"
# postgres = "0.17.4"
# r2d2_postgres = "0.16.0"
rand = "0.7"
reqwest = { version = "0.10.6", features = ["blocking", "json"] }
# serde = { version = "1.0.115", features = ["derive"] }
# serde_json = "1.0.56"
tokio = { version = "0.2", features = ["macros", "rt-core", "time"] }
tracing = "0.1.21"



[dependencies.serenity]
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
]
version = "0.9.0-rc.2"
